project:
  type: website

website:
  title: "Learning Games and Game Building"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.html
        text: Slides
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Planning"
        contents:
          - sections/pedagogy.md
          - sections/design.md
          - sections/storyboarding.md
      - section: "Twine"
        contents:
          - sections/twine-basics.md
          - sections/twine-how-to.md
          - sections/publishing.md
          - sections/twine-resources.md
  page-navigation: true

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

